### ISSUE TITLE
Relative path considerations

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/wcmatch#1]
So the `wcmatch.glob` and `wcmatch.iglob` work on relative paths. The way it works is that `**` does not match `.` and `..`. This makes sense when crawling files. So with globstar enabled and and restricting dots (these may be enabled by default in the future), we get:

```python
>>> glob.glob('**/../*.md', flags=glob.G|glob.D)
['.\\docs\\..\\README.md', '.\\docs\\src\\markdown\\_snippets\\..\\changelog.md', '.\\docs\\src\\markdown\\_snippets\\..\\index.md', '.\\docs\\src\\markdown\\_snippets\\..\\installation.md', '.\\docs\\src\\markdown\\_snippets\\..\\license.md', '.\\requirements\\..\\README.md', '.\\tests\\..\\README.md', '.\\wcmatch\\..\\README.md']
```

But when applying globmatch, these paths don't match:

```python
>>> glob.globmatch('.\\requirements\\..\\README.md', '**/../*.md', flags=glob.G|glob.D)
False
```

The crux of the issue is that when crawling, `.` and `..` have special meaning. So you want to first globstar, then either do nothing for `.` or get the parent for `..`.  So `**` should absolutely not capture parents and continue on. Because then it would just be treated as "another file". `.` is what should be found after `**`, not part of `**`. 

But matching is different when trying to get the same results.  Using the example: `'.\\requirements\\..\\README.md'`, we are using simple pattern matching.  It must be noted if `**` can't match a hidden file `.hidden`, `**` so it should be safe. `.` is the same path that you already matched, so we know it is good as well.  It can also represent the current directory.  In the context of matching a glob path, restriction of dot is meant to ignore `.hidden` files, not special directory specifiers.

I think `**` should be able to to match specifically `.` and `..`, but not `.hidden`. `*` should be able to match `.` and `..` as well.  At least in `globmatch`. This could be debated for `fnmatch`.

- `globmatch` should probably match separators as `(?:/\.(?=/|$)|/)+` to match cases like `/file////name/././`  These are stupid ways to write file names, but they should match. If this was on the end of a globstar pattern, it would naturally gather `./` paths.
- If a path does not start with a windows drive or slash, `./` should be an optional assumption `(?:\.(?:/\.(?=/|$)|/)+)?`.

Just some thoughts.  I obviously need to think out these cases well enough to construct a regex that isn't unnecessarily ridiculous.  Maybe our fnmatch needs to just match file names, and globmatch just do directories. Or maybe globmatch doesn't need to be a regex.  It might actually be easier to use the same glob logic minus file crawling.

**Comment by facelessuser** [comment]
The actual issue escaped me at first.  `**/../*.md` should not return paths with a `.`.  The mistake is not that it can't match them, is that the return is inconsistent for the pattern. 🤦‍♂️ .

**Comment by daturkel** [comment]
Hi, sorry to revive an old issue, but I'm having trouble understanding how relative paths are handled.

In particular, Pathlib says that:
`Path('to/a/file') == Path('./to/a/file')`

But if `p` is a path equal to the above, I get that:
```{python}
p = Path('./to/a/file') # => Path('to/a/file')
p.globmatch('to/a/*') # => True
p.globmatch('./to/a/*') # => False
```

Furthermore, the `DOTMATCH` flag doesn't  make the second expression evaluate to True either. What can I do to make that second line a match?

**Comment by facelessuser** [comment]
In order understand what is happening, we need to show you the difference in how a normal glob in Bash works:

```cmd
$ echo ./wcmatch/*.py
./wcmatch/__init__.py ./wcmatch/__meta__.py ./wcmatch/_wcparse.py ./wcmatch/fnmatch.py ./wcmatch/glob.py ./wcmatch/pathlib.py ./wcmatch/util.py ./wcmatch/wcmatch.py
```

and

```cmd
$ echo wcmatch/*.py
 wcmatch/__init__.py wcmatch/__meta__.py wcmatch/_wcparse.py wcmatch/fnmatch.py wcmatch/glob.py wcmatch/pathlib.py wcmatch/util.py wcmatch/wcmatch.py
```

1. So, we see that the glob pattern `./wcmatch/*.py` returns things like this: `./wcmatch/__init__.py`.
2. We see that the glob pattern `wcmatch/*.py` returns things like this: `wcmatch/__init__.py`.
3. We note in our documentation that `globmatch` matches what `glob` globs.
4. `./wcmatch/*.py` does not match `wcmatch/__init__.py`. It expects a current directory indicator which is `.`.

Yes, it matches relative directories, but you need to match them in the format that they are.

Pathlib strips things like `./` from a path:

```
>>> import pathlib
>>> p = pathlib.Path('./relative/path')
>>> print(p)
relative/path
```

So you need to match it as Pathlib serves it, without the `./`. It has nothing to do with `DOTMATCH`.

I the future, please do open a new issue instead of necroing an old issue. I don't mind things being asked again in a new issue.

**Comment by daturkel** [comment]
Thanks for taking the time for the thorough response! This is helpful. I guess I had just expected that if pathlib treats './foo' and 'foo' the same that other path-adjacent tools might, but your explanation makes sense to me.

**Comment by facelessuser** [comment]
It seems that pathlib's match does support `./relativepath`. I assume they strip preceding paths. It is possible we could do something similar. Can you open an issue? We may want to at least consider this to in our pathlib implementation to match the original. I am open to considering it.

**Comment by facelessuser** [comment]
If we decide against it, at the very least we should document the difference, but as our implementation is meant to be an enhance alternative, it may be worth it to add matching logic as to not catch people off guard.

**Comment by facelessuser** [comment]
Hmm. They appear to also match things like this:

```
>>> p.match('./docs/./src/./markdown')
True
```

I think this is because Python's implementation simply breaks apart the path pattern and when it sees `.` it just ignores it. We on the other hand generate a pattern that matches the path. Our implementations are just very different.

What it boils down to is a pros and cons. If being agnostic to relative dots is important for how you use path matching, then use the builtin Python version. If the other features that wcmatch offers is more important, then I'd use that. I'm not sure I want to adjust are patterns to match `.` directories automatically. But I should at least document this difference.

**Comment by facelessuser** [comment]
Yeah, it's definitely not truly handling relative paths. They don't consider `..`, they just selectively ignore `.`:

```
>>> p.match('./docs/./src/../src/./markdown')
False
```

At first glance, it gives you the impression that are checking relative paths, but they really aren't.

**Comment by facelessuser** [comment]
Differences are now documented: https://facelessuser.github.io/wcmatch/pathlib/#differences.

**Comment by facelessuser** [comment]
For anyone reading this in the future, it is cases like this that make me not want to match Python's Pathlib default match logic:

```py
>>> import pathlib
>>> p = pathlib.Path('relative/file.py')
>>> p.match('relative/file.py/.')
True
```

It's very naive, and I think our approach makes more sense. Considering that Pathlib strips all relative `.` from the pattern, this is no reason to have these in a Pathlib match pattern. At most, I would consider stripping leading `./` from a pattern as a convenience (maybe), but I don't think we would ever crawl the entire pattern removing every instance of `.`.
