### ISSUE TITLE
We don't need external mock module anymore

### ISSUE THREAD

**Issue by mcepl** [facelessuser/wcmatch#108]
Mock library is now included in the Python standard library (since 3.3). I don’t care about attribution for [the patch](https://github.com/facelessuser/wcmatch/files/4794593/dont-use-mock.patch.txt), you can just merge it.

**Comment by facelessuser** [comment]
Cool, thanks for reporting it. Old habits and all that 🙂.

@gir-bot remove S: triage
@gir-bot add T: Maintenance, C: tests
