### ISSUE TITLE
Unable to glob inverse match

### ISSUE THREAD

**Issue by rahiparikh** [facelessuser/wcmatch#137]
Hello,

Thank you for building this library. I am trying to find all files in a directory (recursively) that do not match any pattern.

```
% tree -a  
.
├── docs
│   ├── subdir1
│   │   ├── fileX
│   │   ├── fileY
│   │   └── fileZ
│   ├── subdir2
│   │   ├── fileX
│   │   ├── fileY
│   │   └── fileZ
│   └── subdir3
│       ├── fileX
│       ├── fileY
│       └── fileZ
├── package.json
├── packages
│   ├── subdir1
│   │   ├── fileX
│   │   ├── fileY
│   │   └── fileZ
│   ├── subdir2
│   │   ├── fileX
│   │   ├── fileY
│   │   └── fileZ
│   └── subdir3
│       ├── fileX
│       ├── fileY
│       └── fileZ
└── .yarn

8 directories, 20 files
```
I am using the following sample python code to exclude the patterns.
```python
from wcmatch import glob

root = "/tmp/glob_tester"
flags = glob.IGNORECASE | glob.GLOBSTAR | glob.NEGATE | glob.MATCHBASE | glob.DOTGLOB | glob.NODIR
skipped_patterns = ["**", "!(**/subdir2/**, **/docs/**/fileX, **/.yarn)"]
included_files = glob.glob(skipped_patterns, flags=flags, root_dir=root)
```
This code returns the following list of files:
```
- docs/subdir2/fileY
- docs/subdir2/fileZ
- docs/subdir2/fileX
- docs/subdir1/fileY
- docs/subdir1/fileZ
- docs/subdir1/fileX
- docs/subdir3/fileY
- docs/subdir3/fileZ
- docs/subdir3/fileX
- .yarn
- package.json
- packages/subdir2/fileY
- packages/subdir2/fileZ
- packages/subdir2/fileX
- packages/subdir1/fileY
- packages/subdir1/fileZ
- packages/subdir1/fileX
- packages/subdir3/fileY
- packages/subdir3/fileZ
- packages/subdir3/fileX
```

Am I approaching the idea incorrectly?

**Comment by facelessuser** [comment]
`NEGATE` allows you to do inverse patterns. Looks like you have multiple. This should work:

```
skipped_patterns = ["**", "!**/subdir2/**", "!**/docs/**/fileX", "!**/.yarn"]
```

You could pair `NEGATE with `BRACE` and do it as shown below. `BRACE` will basically just expand to what I did above.

```
skipped_patterns = ["**", "!{**/subdir2/**,!**/docs/**/fileX,!**/.yarn}"]
```

The problem was that you were trying to use the `EXTGLOB` pattern style of `!()`. This is a BASH feature which:

1. separates patterns with `|` not `,`.

2. applies to file names, not file paths.

**Comment by facelessuser** [comment]
Moving to support as behavior appears to be as expected. Let me know if you figured out your issue or not, or if you need more info.

@gir-bot add T: support
@gir-bot remove S: triage

**Comment by rahiparikh** [comment]
Thank you for pointing me in the right direction. The first suggestion did the trick. I was wondering, based on your second suggestion, if the library could be the victim of denial of service if user supplied patterns are used. Thoughts?

**Comment by facelessuser** [comment]
Can you explain further? Are speaking of someone using a pattern that expands to unusually large sizes?

**Comment by facelessuser** [comment]
If you are worried about massive expanding patterns, we do limit how many patterns we proceed: https://facelessuser.github.io/wcmatch/glob/#multi-pattern-limits.

**Comment by facelessuser** [comment]
As questions were answered, closing issue as resolved.
