### ISSUE TITLE
Provide a method to determine if a pattern is magic

### ISSUE THREAD

**Issue by inkychris** [facelessuser/wcmatch#155]
It would be useful to have a function that returns a bool value of whether or not the pattern provided is "magic" or not.

An example (which I need) where this would be useful is in determining the concrete base path of a pattern:
- `path/to/something/**/test*` > `path/to/something`.

As a work around, I can just use the regex included in the library, or compare the pattern with its glob-escaped counterpart, but ideally this would be addressed by a dedicated function in the package.

**Comment by facelessuser** [comment]
I'm not sure I completely understand your use case, or how exactly you expect this `is_magic` function to help you determine the base path, can you elaborate?

---

On a side note, it is important to note that:

1. On Windows, if you use backslashes as path separators, they will always come up as magic, so you would be forced to use `/` except when escaping characters, using character escapes in raw strings (via the `RAW_CHARS` flag.

2. Additionally, on Windows, there are UNC paths. UNC paths in `wcmatch` can never be magic. We don't allow magic patterns in a UNC path as it is impossible, or highly inefficient, to try and discover all possible network mounts and glob them. For instance, `//?/UNC/server/mount` is a valid UNC path, and we don't want to discover all possible network connections available, so `?` isn't treated as magic (this is covered in the documentation). Anything after the UNC server/mount would be treated as a normal glob pattern.

3. Also, keep in mind, due to all the features in `wcmatch`, it is much more aggressive in erring on the side of magic. For instance, we have an option where you can have a pattern be an exclusion pattern by having it start with `-` (default is `!`), so any pattern with `-` will be considered magic. It just conservatively escapes based on the general "possible" feature set. If I could go pack in time, I'd probably not have added `-` as an exclusion, but there were reasons at the time which I won't go into here.

---

So, I could add a function like this. Assuming you do not use Windows backslashes as path separators and instead use `/`, you don't use UNC paths, and you are okay with something more benign like `-` counting as magic, this would work (use `raw_chars` if you are using a raw string and wish to translate character escapes such as `\N{UNICODE NAME}`, `\u0245`, etc., backslashes are magic anyway, so maybe we could simply omit `raw_chars` being needed to pass in).

```py
def is_magic(pattern, unix=None, raw_chars=False):
    """Check if the path is likely to be magic."""

    escaped = raw_escape(pattern, unix, raw_chars)
	return escaped != pattern
```

**Comment by facelessuser** [comment]
I guess we could make `is_magic` feature aware and only flag certain magic things if feature X is enabled, but then you need to pass the feature flags.

**Comment by facelessuser** [comment]
I take it back UNC passes through fine, it's just the backslashes, which makes sense. You can use UNC with forward slashes.

```py
>>> glob.is_magic('//?/server/mount/am/I/magic', unix=False)
False
```

While Windows users can use backslashes, we advise they use forward, but we'll work either way.

The question is whether we need to accept flags and control the level of magic detection. I don't think escape needs to change, it can remain conservative, but `is_magic` I feel would need to be aware of enabled features and be less conservative or more depending on the enabled features.

I'm still not quite sure how you are using this, but this is just my initial thinking out loud of what needs to happen if we go down this road.

**Comment by inkychris** [comment]
I was expecting it would be a function with a similar signature to `wcmatch.pathlib.globmatch`.

I have a utility class called `FileMap` which provides a common interface for defining source-destination mappings of files to and from local files, local archives (tarball and zips), and webservers (in my case raw repos in Nexus3). The issue I'm trying to address is that currently when talking to Nexus, this utility has to query the contents of the entire Nexus repository. If it has a concrete base path then I can pass that along with the Nexus API call to limit the number of responses which are then globbed with the pattern, e.g: the `project/path/**/*.lib` pattern would only ever match items under the `project/path` directory, so I can tell Nexus to only return items in that directory, which I can then glob with `**/*.lib` to decide which ones should be downloaded, but what I need to do is determine whether a path is "magic" so I can work out what/if I can tell Nexus to limit the API results. If it's magic, then the API query can't be optimised.

**Comment by inkychris** [comment]
In its simplest, it would be a function that tells you whether it's a fully qualified path, i.e. you can use it without using glob at all, or if globbing the pattern would potentially return one or more results. Having said "simplest", I guess that begs the question whether a character class with only one character would be deemed "magic" or not. Behaviour wise I'd have said not, e.g. `tes[t]` would only ever match the concrete string `test`, right?

**Comment by facelessuser** [comment]
Yes, you are looking for a literal path. And yes we can do this excluding the use of Windows backslash. We just need to make it aware of features via flags.

But, what I'm not understanding is how `is_magic` is going to get you the base path of `project/path/**/*.lib`. If you want to filter files under a base path, can't you pass a base path into `globmatch` with `root_dir`?

```py
>>> glob.globmatch('project/path/folder/file.lib', '**/*.lib', root_dir='project/path', flags=glob.G)
True
```

I guess I'm not understanding the use case still.

**Comment by inkychris** [comment]
So my problem is that at the point where I'm doing the actual globbing, I don't know if the end user has provided a pattern that is exclusively "magic", i.e. it doesn't have any literal path prefix, or if it has one or more literal directories included in it itself. From my perspective, I just have one pattern that may or may not correctly be split between `root_dir` and `pattern`. On top of this, I need to figure out what these base paths are *before* I do the globbing, since the globbing is performed on a list of paths returned by the Nexus API call.

**Comment by facelessuser** [comment]
So, you are expecting that is_magic will return literal and magic parts? Sounds like a pretty advanced function you are asking for. Do you plan on iterating your path with `os.path.dirname()` passing the result into `is_magic` until you get the result you are looking for?

Can you pseudo code what you are requesting us to do and how you expect it to behave? I thought you wre asking for a simple `is_magic` function, but the more you explain, the more I think that is not what you are asking for?

**Comment by facelessuser** [comment]
Let me clarify, pseudo code the API, not the guts. I need to understand inputs and outputs.

**Comment by inkychris** [comment]
I was imagining the function would simply return a bool of whether it is magic or not. In my case, I'm then iteratively removing parts of the path until it's either not magic anymore, or there aren't any parts left (the whole thing is magic). Code would look something like this (this should run!):
```python
import wcmatch.pathlib as pathlib


# This is in place of the requested function.
def is_magic(pattern):
    return any(char in '*?!' for char in pattern)


# This is in place of web requests to Nexus
# with `subdir` representing a field in the API
# that can limit the number of items in the reponse.
def remote_api_response(subdir=None):
    files = [f'sub/dir/file{i+1}.txt' for i in range(3)]
    files.extend(f'sub/file{i+1}.md' for i in range(3))
    files.extend(f'file{i+1}.rst' for i in range(3))
    if subdir:
        print(f'limiting API response to subdir {subdir}/*')
    else:
        print('Full API response')
    for file in files:
        if subdir is None or file.startswith(subdir):
            yield file


# This represents the interface my end-user has.
# In reality slightly more comprehensive
# but it boils down to only having a single pattern.
def remote_files(pattern):
    subdir = pathlib.Path(pattern)
    while len(subdir.parts):
        if is_magic(subdir.as_posix()):
            subdir = subdir.parent
        else:
            break
    if not len(subdir.parts):
        subdir = None
    for file in remote_api_response(subdir=subdir.as_posix() if subdir else None):
        if pathlib.Path(file).globmatch(pattern, flags=pathlib.GLOBSTAR + pathlib.DOTMATCH):
            yield file


# Example consumer which in reality
# would be taking the "items" returned by the API
# and then downloading them.
def list_files(pattern):
    for file in remote_files(pattern):
        print(' -', file)
    print()


list_files('**/*.txt')
list_files('sub/**/*')
list_files('su*/**/*')
```
Like you say, it would make sense for this to accept flags so the `is_magic` call would probably look the same as the `globmatch` call.

**Comment by facelessuser** [comment]
Okay, if all you need from wcmatch is an `is_magic` that takes a pattern and returns a bool, we can probably do that. We can give it a little more intelligence than escape which just conservatively escapes anything that "might" be magic. It will be noted that backslashes will always make a path "magic" (sorry Windows, use forward slashes).

I imagine it will look simply like:

```py
def is_magic(pattern: Union[str,bytes], *, flags int = 0) -> bool: ...
```

Keep in mind though, it won't look to see if is actually magic. For instance `patter[more` won't actually be magic, even though it has `[` in it, but `pattern[more]` would be magic. It more will look for the likeliness of "magic".

**Comment by inkychris** [comment]
Sounds good, thanks for looking into it!

**Comment by facelessuser** [comment]
#156 will address this feature request. I still need to write tests for it to make sure I'm not missing any corner cases, but you are welcome to test it and see if it meets your needs.

**Comment by inkychris** [comment]
Tried it out properly and looks like it does everything I need!

**Comment by facelessuser** [comment]
Okay, I'll work towards getting it tested and such and it should be available in the next release.

**Comment by inkychris** [comment]
Amazing, thank you for working on it so quickly!

**Comment by facelessuser** [comment]
No problem, it helps that it is something I've been considering already, I just never had a direct need or request for it until now 🙂.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: feature
