### ISSUE TITLE
is_unique reverses the case logic

### ISSUE THREAD

**Issue by flolf** [facelessuser/wcmatch#164]
`if (path.lower() if self.case_sensitive else path) not in self.seen` is incorrect and should be
`if (path if self.case_sensitive else path.lower()) not in self.seen`.

**Comment by facelessuser** [comment]
Great catch!

@gir-bot add T: bug, S: confirmed
@gir-bot remove S: triage

**Comment by facelessuser** [comment]
@flolf Did you catch this by inspection or run into a real world issue? More curious than anything. It is likely rare that people would run into this issue, but still possible.

**Comment by flolf** [comment]
It was a real life issue. I had two different files with two different name but because they happen to have the same lowercase version one of them got dropped. I just started using wcmatch yesterday but since the file system I use is case sensitive I quickly ran into this issue.

**Comment by facelessuser** [comment]
In that case, I'll go ahead and push the release. I rarely have multiple files with different cases, but I know it is certainly possible.

**Comment by facelessuser** [comment]
8.1.1 is live

**Comment by flolf** [comment]
Great, thanks for the fast turnaround.

**Comment by facelessuser** [comment]
No problem. I probably need to cobble up a test case on Linux systems that exercises this exact scenario. We have plenty that test case sensitive matching vs insensitive, but not specifically checking the unique cache's logic in this area.
