### ISSUE TITLE
Test tests.test_glob.TestTilde is failing

### ISSUE THREAD

**Issue by pnemade** [facelessuser/wcmatch#171]
I am packaging this project for Fedora Linux. While doing that it is found that the testcase `tests.test_glob.TestTilde` is failing.
More information is at https://bugzilla.redhat.com/show_bug.cgi?id=1929992#c2

Let me also give here exact error.
```
======================================================================
ERROR: test_tilde_user (tests.test_glob.TestTilde)
Test tilde user cases.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/wcmatch-8.1.2/tests/test_glob.py", line 1480, in test_tilde_user
    files = os.listdir(os.path.expanduser('~{}'.format(user)))
FileNotFoundError: [Errno 2] No such file or directory: '~builddir'
----------------------------------------------------------------------

```

**Comment by frenzymadness** [comment]
Useful comments from the bugzilla:
* This test has wrong assumptions (that username == basename(homedir)).
* Replacing os.path.basename(os.path.expanduser('~')) with getpass.getuser() should fix the test.

**Comment by facelessuser** [comment]
I now recall why I didn't use `getpass`: https://github.com/facelessuser/wcmatch/pull/172/checks?check_run_id=2076684371#step:6:71.

I hadn't remembered until I tried this again, but I did go down this road before. In Windows CI and such, `import pwd` fails. I guess this is not guaranteed to be on all systems.

I'll see if I can rework the test to fall back to the old methodology if `getpass` fails.

**Comment by facelessuser** [comment]
I imagine that `getpass` works most places except maybe on Windows, (or at least some Windows machines). I think the old approach is pretty reliable for a Windows box, but less reliable for a Linux box. Either way, on `master`, we now attempt `getpass`, and if that fails, we attempt the old `basename(homedir)` approach.

@pnemade, if this is strongly needed in an official release, I can probably cut a post-release; otherwise, it will be in the next release whenever that it is. Just let me know if if you need a release now.

**Comment by frenzymadness** [comment]
In Fedora, we can simply skip the test and wait for the next release. Thanks for the quick fix!

**Comment by facelessuser** [comment]
@frenzymadness, thanks for the follow-up. Then we will wait until we accrue some release worthy changes.

**Comment by pnemade** [comment]
Yes it is fine, that test can be skipped for now. When new upstream release will happen, I will update the Fedora package.
Thank you both for quickly looking into this issue.
