### ISSUE TITLE
EXTGLOB extended patterns not working

### ISSUE THREAD

**Issue by beatreichenbach** [facelessuser/wcmatch#174]
I can't get the extended patterns to work whether it is with glob.glob or glob.globmatch. I am trying with the example provided in the docs:
https://facelessuser.github.io/wcmatch/glob/#globmatch
I'm also making sure to use a Python version higher than 3.6.
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
`>>> from wcmatch import glob
>>> glob.globmatch('some/path/test.txt', r'**/*/@(*.txt|*.py)')
False`

more simplified also doesn't work:
`>>> glob.globmatch('test.txt', r'@(*.txt|*.py)')
False`

but without the extended pattern it works:
`>>> glob.globmatch('test.txt', r'*.txt')
True`

**Comment by facelessuser** [comment]
> I can't get the extended patterns to work

@beatreichenbach This is because you need to enable EXTGLOB by setting the flag 😉 .

```py
>>> from wcmatch import glob
>>> glob.globmatch('some/path/test.txt', r'**/*/@(*.txt|*.py)', flags=glob.EXTGLOB)
True
```

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Closing as there is no actionable item. The problem was a result of incorrect usage.

**Comment by beatreichenbach** [comment]
Oh thank you for the quick reply!
I got that example straight from the documentation.

This actually let me to figure out what my initial issue was. It seems like backslashes don't work in the package. So while this works:
`glob.glob(r'**/*@(.jpg|.exr)', flags=glob.EXTGLOB)`

using backslashes on windows doesn't work:
`glob.glob(r'**\*@(.jpg|.exr)', flags=glob.EXTGLOB)`

However using backslashes in the original glob package does work.

**Comment by facelessuser** [comment]
> I got that example straight from the documentation by the way.

If I have a bad example, that needs to be fixed.

**Comment by facelessuser** [comment]
I assume you figured it out, but since I saw this statement in my email, I just figured I'd respond. 

> It seems like backslashes don't work in the package.

`wcmatch` allows for using back slashes to escape. So `\*` is an escaped asterisk. You can escape in the traditional way as weill `[*]`, but you can also use backslashes. Because of this, you must use a double backslash for a Windows directory: `r"this\\that"`. This is covered in the documentation.

I figured you already figured it out as your comment above has been edited, but maybe it will help others.

**Comment by beatreichenbach** [comment]
Yeah I got the example from that link that I posted in my first post under #globmatch.
And yeah, I figured out the backslash issue as you clearly mentioned it right at the beginning of the documentation in the Tip. Thanks again! :)

**Comment by facelessuser** [comment]
Yeah, most of the examples were copied and pasted from the terminal, but there were a few that were doctored were copied and doctored. This appears to be a case where I doctored the example and accidentally deleted the flags 🤦🏻.
