### ISSUE TITLE
Expose `PATHNAME` flag to `fnmatch`?

### ISSUE THREAD

**Issue by yedpodtrzitko** [facelessuser/wcmatch#204]
Hi,
I'd like to have `fnmatch` behaving similar way as `glob()`/`wcmatch()`, where `*` would match only one level of directories:

```
fn = fnmatch('a/b/c/z.txt', 'a/*/z.txt')

fn.match('a/x/z.txt') # True
fn.match('a/b/c/z.txt') # True (I'm expecting False here)
```

this would work as expected:
```
fn = fnmatch('a/b/c/z.txt', 'a/*/z.txt', flags=_wcparse.PATHNAME)
```
however the flag `PATHNAME` is not allowed in `fnmatch()`, and it gets stripped via `_flag_transform()`.

Would you accept PR exposing the flag there? Or is there any way how to achieve this behaviour currently? Thanks.

**Comment by facelessuser** [comment]
@yedpodtrzitko Sounds like you want to use [`globmatch`](https://facelessuser.github.io/wcmatch/glob/#globmatch) instead of `fnmatch`. `fnmatch` does file name matching, not path matching. `globmatch` matches file glob paths.

**Comment by facelessuser** [comment]
For example:

```py
>>> from wcmatch import glob
>>> glob.globmatch('a/b/c/z.txt', 'a/**/z.txt', flags=glob.GLOBSTAR)
True
```

**Comment by yedpodtrzitko** [comment]
Thanks for your comment. Unfortunately I dont work directly with a filesystem, but with a list of paths returned from API representing filesystem. And I need to filter this list using the glob-like patterns, but since it's not filesystem the only tool I can use is `fnmatch`.

**Comment by facelessuser** [comment]
Please read the section I linked. The documentation states:

> By default, globmatch and globfilter do not operate on the file system. This is to allow you to process paths from any source, even paths that are not on your current system.

You can figure it to use Windows or Unix patch logic, depending on what you need.

**Comment by facelessuser** [comment]
For clarification, if `fnmatch` were to use `PATHNAME`, it would operate exactly like `globmatch`, so what you want is `globmatch`.

**Comment by yedpodtrzitko** [comment]
Ah ok, that does the trick. Thanks
