### ISSUE TITLE
Order of magic and non-magic patterns breaks the glob result

### ISSUE THREAD

**Issue by tomfen** [facelessuser/wcmatch#205]
Using mixed magic and non-magic patterns like
```python
# this_script.py
from wcmatch.glob import glob

patterns = ["**/this_script.py", "dummy"]

print(
    glob(patterns),
    glob(patterns[::-1])
)
```
I expect both results to contain the "this_script.py". If all the magic patterns are before others this works fine, otherwise the results are broken - in this case empty.

the culprit seems to be line https://github.com/facelessuser/wcmatch/blob/223f9caba2a4d9ce6b796d890693773e9c5d4080/wcmatch/glob.py#L810  The variable is overwritten in the loop, affecting the call to `_glob` later.

**Comment by facelessuser** [comment]
We should have been restoring `curdir` each iteration of the loop. Good catch! Fix is in the referenced PR.

**Comment by facelessuser** [comment]
I'm actually surprised this hadn't been caught long before now. We at least have tests covering this moving forward.

**Comment by facelessuser** [comment]
Fix has been released
