### ISSUE TITLE
feature request: wcmatch.glob.NOFILE (analog to wcmatch.glob.NODIR)

### ISSUE THREAD

**Issue by timotheecour** [facelessuser/wcmatch#220]
feature request: wcmatch.glob.NOFILE (analog to wcmatch.glob.NODIR).
I'm not sure if it's the right api but it would be useful to only retrieve dirs, not files.
An alternative would be to allow specifying what kind we want to retrieve (eg symlinks, files, dirs etc)

**Comment by facelessuser** [comment]
The reason why there is not an analogous flag to `NONDIR` is simply because it is easy to request only directories, but not files only. Simply end your pattern with a directory separator.

```python
>>> from wcmatch import glob
>>> glob.glob('*/')
['dist/', 'tests/', 'wcmatch/', 'requirements/', '__pycache__/', 'docs/', 'site/', 'build/']
```

**Comment by timotheecour** [comment]
true but then you have to post-process results to remove trailing `/`
not a huge deal, admittedly

**Comment by facelessuser** [comment]
> true but then you have to post-process results to remove trailing / (assuming that's what user wants, in general)
not a huge deal, admittedly

I admit, I'm not sure this would be a noteworthy nuisance. Though, of course, this is a subjective opinion :).

> A bigger problem could be if this is part of an API (as is my case), eg:

If I'm being honest, I think this is a trivial problem to solve, assuming you approach it from a different angle than post-processing patterns:

```py
from wcmatch import glob
import os


def myglob(pattern, with_dirs=False, with_files=True, flags=0):
    if with_files:
        return glob.glob(pattern, flags=flags if with_dirs else flags | glob.NODIR)
    elif with_dirs:
        return [r for r in glob.glob(pattern) if os.path.isdir(r)]
```

```py
>>> from myglob import myglob
>>> myglob('*', with_dirs=True, with_files=True)
['LICENSE.md', 'mkdocs.yml', 'dist', 'myglob.py', 'pyproject.toml', 'tests', 'wcmatch', 'requirements', '__pycache__', 'docs', 'README.md', 'hatch_build.py', 'site', 'coverage.xml', 'build']
>>> myglob('*', with_dirs=False, with_files=True)
['LICENSE.md', 'mkdocs.yml', 'myglob.py', 'pyproject.toml', 'README.md', 'hatch_build.py', 'coverage.xml']
>>> myglob('*', with_dirs=True, with_files=False)
['dist', 'tests', 'wcmatch', 'requirements', '__pycache__', 'docs', 'site', 'build']
>>> myglob('*', with_dirs=False, with_files=False)
>>>
```
