### ISSUE TITLE
glob: Inconsistent behavior with symlinks

### ISSUE THREAD

**Issue by IgorEisberg** [facelessuser/wcmatch#222]
Hey, so I'm using the following setup:
```
    flags = NEGATE | DOTGLOB | EXTGLOB | GLOBSTAR | BRACE | SPLIT | NEGATEALL | GLOBTILDE | NODOTDIR

    matches = [
        match for match in glob(pattern, flags=flags)
        # rest of code
    ]
```

I know that when using the pattern '**', it does not follow symlinks by default. The problem is that the symlink is completely missing in the results like it doesn't exist. It would be nice to have the option to glob without following symlinks at all and treating them as a path to a normal file (like the default behavior of `find` command which includes symlinks in the results but doesn't resolve or follow them by default).

**Comment by facelessuser** [comment]
This is a reasonable request and is how Bash works. I can't recall my reasoning as to why I excluded them. The flag was meant to prevent following, but, obviously, we are completely excluding them...

**Comment by facelessuser** [comment]
It seems the fix should be pretty straightforward. I need to write some additional tests for `globmatch` with `REALPATH` enabled though.  I imagine I can get a new release out either today or tomorrow.

**Comment by facelessuser** [comment]
@IgorEisberg Just to make sure, you are requesting to also keep the ignoring behavior of symlinks under an option as well?

**Comment by facelessuser** [comment]
My initial inclination is to just match Bash by matching symlinks while avoiding following them. So the `FOLLOW` flag only controls traversal of symlink following, not symlink matching.

**Comment by facelessuser** [comment]
I've chosen currently to just change the behavior. Our goal was generally to target Bash behavior, and we were not following it here.

**Comment by IgorEisberg** [comment]
Man, you are lightning fast. Thanks for handling this. Installed with `pip install git+https://github.com/facelessuser/wcmatch.git#egg=wcmatch` and now everything seems to work as expected.
Yeah, I mean I thought symlinks were never followed unless FOLLOW flag is used, just made sense. :D
wcmatch's glob has been a robust basis for my CLI tool to resolve paths according to various options, so thank you very much.

**Comment by facelessuser** [comment]
Glad it is working for you. I should get a release out soon-ish.
